### ISSUE TITLE
Change the center of the map

### ISSUE THREAD

**Issue by pronebird** [zcreativelabs/react-simple-maps#23]
Hi,

I am trying to shift the center of the map a little bit up to make some space for overlay UI, so I used `yOffset` for that but I get pretty weird results, i.e misplaced markers etc...

I pretty much follow the following example:
https://www.react-simple-maps.io/with-react-motion

This is my projection configuration:

```
projectionConfig = {
  yOffset: -150 / this.state.zoom
}
```

**Comment by zimrick** [comment]
Hmm, normally I would use the `center` prop on the `ZoomableGroup` (set to `[0,20]`) to move the map up a little bit. Is there any reason you would want to use yOffset in specific, or does this achieve the same thing?

**Comment by pronebird** [comment]
I thought `center` is a geo coordinate. I'd like to visually offset the map off the center by X pixels.

**Comment by zimrick** [comment]
Yeah, center is a geo coordinate that sets the focus of the map. It would achieve a similar result, i.e. moving your map up or down, depending on the coordinate that the map focuses on by default.

I am having trouble recreating the problem with `yOffset` and the misplaced markers. I tried this and it works. Am I missing something?

```js
class OffsetMap extends Component {
  render() {
    return (
      <div>
        <ComposableMap
          projectionConfig={{
            yOffset: 50,
          }}
          style={{
            border: "1px solid #DDD",
          }}
          >
          <ZoomableGroup zoom={1}>
            <Graticule />
            <Geographies geographyUrl="/static/world-50m.json">
              {(geographies, projection) =>
                geographies.map((geography, i) =>
                  <Geography
                    key={i}
                    geography={geography}
                    projection={projection}
                    style={{ default: { fill: "#DDD" } }}
                  />
              )}
            </Geographies>
            <Markers>
              <Marker marker={{ coordinates: [8.5417,47.3769] }}>
                <circle cx={0} cy={0} r={5} />
              </Marker>
              <Marker marker={{ coordinates: [103.8198,1.3521] }}>
                <circle cx={0} cy={0} r={5} />
              </Marker>
              <Marker marker={{ coordinates: [151.2093,-33.8688] }}>
                <circle cx={0} cy={0} r={5} />
              </Marker>
              <Marker marker={{ coordinates: [-122.4194,37.7749] }}>
                <circle cx={0} cy={0} r={5} />
              </Marker>
              <Marker marker={{ coordinates: [-58.3816,-34.6037] }}>
                <circle cx={0} cy={0} r={5} />
              </Marker>
            </Markers>
          </ZoomableGroup>
        </ComposableMap>
      </div>
    )
  }
}
```

It gives me a map that looks like this:

<img width="816" alt="screen shot 2017-09-30 at 13 08 01" src="https://user-images.githubusercontent.com/7160099/31045287-71daeb58-a5e0-11e7-913e-5ab7b83f922e.png">

Note that if you added your own markers and they are misplaced, it may be that the order of longitude and latitude is reversed. I know this is an issue when working with coordinates from google and d3-geo. Google uses `[lat,long]` and d3-geo uses `[long,lat]`. `React-simple-maps` uses the d3-geo order. If this is the case, you would be getting very strange results, but if you are using the motion example with the markers that are included there, this shouldn't be a problem...

**Comment by pronebird** [comment]
I will try to reproduce that on Monday and get back to you. The marker I have is created dynamically and its coordinate coincides with the center of the map. Maybe something does not re-render properly...

**Comment by pronebird** [comment]
The problem occurs when using dynamic `yOffset` when zooming, i.e:

```
const yOffset = -20 / this.state.zoom;

///...

<ComposableMap
              projectionConfig={{ scale: 205, yOffset: yOffset }}
```

My idea was to zoom into the same center and then shift the map to make sure that the marker is positioned a little bit above the center of the map and not right in the middle.

This is the changeset based around example with animated map:

https://github.com/pronebird/react-simple-maps/commit/98f82cc293b7434a50d3b3b6ffd47fd5ed1604b9

**Comment by pronebird** [comment]
Update: hovering the mouse over the map shifts geometries to the right positions. That's said I don't think any changes to `yOffset` re-render the map layer. I believe this is a bug in `componentShouldUpdate` or something...

**Comment by zimrick** [comment]
Check: https://github.com/zcreativelabs/react-simple-maps#Geographies-component

I introduced a newer way of optimising the map in v0.7.0. The old way still works, and I tried to avoid introducing breaking changes, hence `disableOptimization` is off by default, but if you use the `cacheId` method you should get good performance with optimization "disabled". Here's how to do that:

```js
<Geographies geographyUrl="/static/world-50m.json" disableOptimization>
  {(geographies, projection) => geographies.map((geography, i) => (
    <Geography
      key={i}
      cacheId={`path-${i}`}
      geography={geography}
      projection={projection}
    />
  ))}
</Geographies>
```

Sorry that this is confusing at the moment, but it should resolve this problem.

**Comment by pronebird** [comment]
It's a little more sluggish I think, but the problem remains the same. :(

**Comment by pronebird** [comment]
I solved the problem by adjusting the center.

```
const zoomOffset = [0, -150];
const zoomCenter= projection.invert([
  projection(center)[0] + zoomOffset[0] / zoom,
  projection(center)[1]  + zoomOffset[1] / zoom
]);
```

**Comment by Jehutty** [comment]
can you give the full code example on how you solved it?
